#pragma once
#include "saved_games/game_variant.h"
#include "tag_files/string_id.h"
#include "tag_files/tag_block.h"
#include "tag_files/tag_reference.h"

#define k_maximum_game_setting_blocks 40
#define k_maximum_text_value_pair_blocks 32
#define k_maximum_text_value_pairs_new_per_block k_maximum_text_value_pair_blocks
#define k_maximum_default_variants 100
#define k_number_of_editable_game_variant_parameters 112

/* enums */

enum e_default_variant_definition_type : uint32
{
	_default_variant_definition_type_slayer,
	_default_variant_definition_type_oddball,
	_default_variant_definition_type_juggernaut,
	_default_variant_definition_type_king,
	_default_variant_definition_type_ctf,
	_default_variant_definition_type_assault,
	_default_variant_definition_type_territories,
	_default_variant_definition_type_head_hunter,

	k_default_variant_definition_type_count,
	k_default_variant_definition_type_base_count = 7
};

enum e_variant_setting_category_type : uint32
{
	_variant_setting_category_type_match_ctf,
	_variant_setting_category_type_match_slayer,
	_variant_setting_category_type_match_oddball,
	_variant_setting_category_type_match_king,
	_variant_setting_category_type_match_race,
	_variant_setting_category_type_match_head_hunter,
	_variant_setting_category_type_match_juggernaut,
	_variant_setting_category_type_match_territories,
	_variant_setting_category_type_match_assault,
	_variant_setting_category_type_players,
	_variant_setting_category_type_OBSOLETE,
	_variant_setting_category_type_vehicles,
	_variant_setting_category_type_equipment,
	_variant_setting_category_type_game_ctf,
	_variant_setting_category_type_game_slayer,
	_variant_setting_category_type_game_oddball,
	_variant_setting_category_type_game_king,
	_variant_setting_category_type_game_race,
	_variant_setting_category_type_game_head_hunter,
	_variant_setting_category_type_game_juggernaut,
	_variant_setting_category_type_game_territories,
	_variant_setting_category_type_game_assault,
	_variant_setting_category_type_quick_options_ctf,
	_variant_setting_category_type_quick_options_slayer,
	_variant_setting_category_type_quick_options_oddball,
	_variant_setting_category_type_quick_options_king,
	_variant_setting_category_type_quick_options_race,
	_variant_setting_category_type_quick_options_head_hunter,
	_variant_setting_category_type_quick_options_juggernaut,
	_variant_setting_category_type_quick_options_territories,
	_variant_setting_category_type_quick_options_assault,
	_variant_setting_category_type_team_ctf,
	_variant_setting_category_type_team_slayer,
	_variant_setting_category_type_team_oddball,
	_variant_setting_category_type_team_king,
	_variant_setting_category_type_team_race,
	_variant_setting_category_type_team_head_hunter,
	_variant_setting_category_type_team_juggernaut,
	_variant_setting_category_type_team_territories,
	_variant_setting_category_type_team_assault,

	k_variant_setting_category_type_count
};

static e_variant_setting_category_type g_variant_setting_category_type_match[k_game_engine_playable_types]
{
	_variant_setting_category_type_match_ctf,
	_variant_setting_category_type_match_slayer,
	_variant_setting_category_type_match_oddball,
	_variant_setting_category_type_match_king,
	_variant_setting_category_type_match_race,
	_variant_setting_category_type_match_head_hunter,
	_variant_setting_category_type_match_juggernaut,
	_variant_setting_category_type_match_territories,
	_variant_setting_category_type_match_assault
};

static e_variant_setting_category_type g_variant_setting_category_type_game_type[k_game_engine_playable_types]
{
	_variant_setting_category_type_game_ctf,
	_variant_setting_category_type_game_slayer,
	_variant_setting_category_type_game_oddball,
	_variant_setting_category_type_game_king,
	_variant_setting_category_type_game_race,
	_variant_setting_category_type_game_head_hunter,
	_variant_setting_category_type_game_juggernaut,
	_variant_setting_category_type_game_territories,
	_variant_setting_category_type_game_assault
};

static e_variant_setting_category_type g_variant_setting_category_type_quick_options[k_game_engine_playable_types]
{
	_variant_setting_category_type_quick_options_ctf,
	_variant_setting_category_type_quick_options_slayer,
	_variant_setting_category_type_quick_options_oddball,
	_variant_setting_category_type_quick_options_king,
	_variant_setting_category_type_quick_options_race,
	_variant_setting_category_type_quick_options_head_hunter,
	_variant_setting_category_type_quick_options_juggernaut,
	_variant_setting_category_type_quick_options_territories,
	_variant_setting_category_type_quick_options_assault
};

static e_variant_setting_category_type g_variant_setting_category_type_team[k_game_engine_playable_types]
{
	_variant_setting_category_type_team_ctf,
	_variant_setting_category_type_team_slayer,
	_variant_setting_category_type_team_oddball,
	_variant_setting_category_type_team_king,
	_variant_setting_category_type_team_race,
	_variant_setting_category_type_team_head_hunter,
	_variant_setting_category_type_team_juggernaut,
	_variant_setting_category_type_team_territories,
	_variant_setting_category_type_team_assault
};

enum e_default_variant_setting_category_type : uint32
{
	_default_variant_setting_category_type_match_round_setting,
	_default_variant_setting_category_type_match_ctf_score_to_win,
	_default_variant_setting_category_type_match_slayer_score_to_win_round,
	_default_variant_setting_category_type_match_oddball_score_to_win_round,
	_default_variant_setting_category_type_match_king_score_to_win_round,
	_default_variant_setting_category_type_match_race_score_to_win_round,
	_default_variant_setting_category_type_match_headhunter_score_to_win_round,
	_default_variant_setting_category_type_match_juggernaut_score_to_win_round,
	_default_variant_setting_category_type_match_territories_score_to_win_round,
	_default_variant_setting_category_type_match_assault_score_to_win_round,
	_default_variant_setting_category_type_match_round_time_limit,
	_default_variant_setting_category_type_match_rounds_reset_map,
	_default_variant_setting_category_type_match_tie_resolution,
	_default_variant_setting_category_type_match_observers,
	_default_variant_setting_category_type_match_join_in_progress,
	_default_variant_setting_category_type_maximum_players,
	_default_variant_setting_category_type_lives_per_round,
	_default_variant_setting_category_type_respawn_time,
	_default_variant_setting_category_type_suicide_penalty,
	_default_variant_setting_category_type_shields,
	_default_variant_setting_category_type_motion_sensor,
	_default_variant_setting_category_type_invisibility,
	_default_variant_setting_category_type_team_changing,
	_default_variant_setting_category_type_team_scoring,
	_default_variant_setting_category_type_friendly_fire,
	_default_variant_setting_category_type_team_respawn_setting,
	_default_variant_setting_category_type_betrayal_respawn_penalty,
	_default_variant_setting_category_type_team_killer_management,
	_default_variant_setting_category_type_slayer_bonus_points,
	_default_variant_setting_category_type_slayer_suicide_point_loss,
	_default_variant_setting_category_type_slayer_death_point_loss,
	_default_variant_setting_category_type_headhunter_moving_head_bin,
	_default_variant_setting_category_type_headhunter_point_multiplier,
	_default_variant_setting_category_type_headhunter_suicide_point_loss,
	_default_variant_setting_category_type_headhunter_death_point_loss,
	_default_variant_setting_category_type_headhunter_uncontested_bin,
	_default_variant_setting_category_type_headhunter_speed_with_heads,
	_default_variant_setting_category_type_headhunter_max_heads_carried,
	_default_variant_setting_category_type_king_uncontested_hill,
	_default_variant_setting_category_type_king_team_time_multiplier,
	_default_variant_setting_category_type_king_moving_hill,
	_default_variant_setting_category_type_king_extra_damage_on_hill,
	_default_variant_setting_category_type_king_dmg_resistance_on_hill,
	_default_variant_setting_category_type_oddball_ball_spawn_count,
	_default_variant_setting_category_type_oddball_ball_hit_damage,
	_default_variant_setting_category_type_oddball_speed_with_ball,
	_default_variant_setting_category_type_oddball_driving_gunning_with_ball,
	_default_variant_setting_category_type_oddball_waypoint_to_ball,
	_default_variant_setting_category_type_race_random_track,
	_default_variant_setting_category_type_race_uncontested_flag,
	_default_variant_setting_category_type_ctf_game_type,
	_default_variant_setting_category_type_ctf_sudden_death,
	_default_variant_setting_category_type_ctf_flag_may_be_returned,
	_default_variant_setting_category_type_ctf_flag_at_home_to_score,
	_default_variant_setting_category_type_ctf_flag_reset_time,
	_default_variant_setting_category_type_ctf_speed_with_flag,
	_default_variant_setting_category_type_ctf_flag_hit_damage,
	_default_variant_setting_category_type_ctf_driving_gunning_with_flag,
	_default_variant_setting_category_type_ctf_waypoint_to_own_flag,
	_default_variant_setting_category_type_assault_game_type,
	_default_variant_setting_category_type_assault_sudden_death,
	_default_variant_setting_category_type_assault_detonation_time,
	_default_variant_setting_category_type_assault_bomb_at_home_to_score,
	_default_variant_setting_category_type_assault_arming_time,
	_default_variant_setting_category_type_assault_speed_with_bomb,
	_default_variant_setting_category_type_assault_bomb_hit_damage,
	_default_variant_setting_category_type_assault_driving_gunning_with_bomb,
	_default_variant_setting_category_type_assault_waypoint_to_own_bomb,
	_default_variant_setting_category_type_juggernaut_betrayal_point_loss,
	_default_variant_setting_category_type_juggernaut_juggy_extra_damage,
	_default_variant_setting_category_type_juggernaut_juggy_infinite_ammo,
	_default_variant_setting_category_type_juggernaut_juggy_overshields,
	_default_variant_setting_category_type_juggernaut_juggy_active_camo,
	_default_variant_setting_category_type_juggernaut_juggy_motion_sensor,
	_default_variant_setting_category_type_territories_territory_count,
	_default_variant_setting_category_type_veh_respawn,
	_default_variant_setting_category_type_veh_primary_light_land,
	_default_variant_setting_category_type_veh_secondary_light_land,
	_default_variant_setting_category_type_veh_primary_heavy_land,
	_default_variant_setting_category_type_veh_primary_flying,
	_default_variant_setting_category_type_veh_secondary_heavy_land,
	_default_variant_setting_category_type_veh_primary_turret,
	_default_variant_setting_category_type_veh_secondary_turret,
	_default_variant_setting_category_type_equip_weapons_on_map,
	_default_variant_setting_category_type_equip_overshields_on_map,
	_default_variant_setting_category_type_equip_active_camo_on_map,
	_default_variant_setting_category_type_equip_grenades_on_map,
	_default_variant_setting_category_type_equip_weapon_respawn_times,
	_default_variant_setting_category_type_equip_starting_grenades,
	_default_variant_setting_category_type_equip_primary_starting_equipment,
	_default_variant_setting_category_type_uns_max_living_players,
	_default_variant_setting_category_type_uns_teams_enabled,
	_default_variant_setting_category_type_uns_assault_bomb_may_be_returned,
	_default_variant_setting_category_type_uns_max_teams,
	_default_variant_setting_category_type_uns_equip_secondary_starting_equipment,
	_default_variant_setting_category_type_uns_assault_fuse_time,
	_default_variant_setting_category_type_uns_juggy_movement,
	_default_variant_setting_category_type_uns_sticky_fuse,
	_default_variant_setting_category_type_uns_terr_contest_time,
	_default_variant_setting_category_type_uns_terr_control_time,
	_default_variant_setting_category_type_uns_oddb_carr_invis,
	_default_variant_setting_category_type_uns_king_invis_in_hill,
	_default_variant_setting_category_type_uns_ball_carr_dmg_resis,
	_default_variant_setting_category_type_uns_king_dmg_res_in_hill,
	_default_variant_setting_category_type_uns_players_ex_dmg,
	_default_variant_setting_category_type_uns_players_dmg_resis,
	_default_variant_setting_category_type_uns_ctf_carr_dmg_resis,
	_default_variant_setting_category_type_uns_ctf_carr_invis,
	_default_variant_setting_category_type_uns_juggy_dmg_resis,
	_default_variant_setting_category_type_uns_bomb_carr_dmg_resis,
	_default_variant_setting_category_type_uns_bomb_carr_invis,
	_default_variant_setting_category_type_uns_force_even_teams,

	k_default_variant_setting_category_type_count
};

enum e_text_value_pair_reference_flags : uint32
{
	_text_value_pari_reference_unused,
	_text_value_pair_reference_default,

	k_text_value_pair_reference_flags_count
};

/* structure */

// max: k_number_of_editable_game_variant_parameters
struct s_default_variant_setting
{
	e_default_variant_setting_category_type type;
	int32 value;
};
ASSERT_STRUCT_SIZE(s_default_variant_setting, 8);


// max: k_maximum_game_setting_blocks
struct s_variant_setting_edit_reference
{
	e_variant_setting_category_type setting_category;

	int32 padding;

	// tag_ref: sily
	tag_block<tag_reference> options;

	int32 unused_1;
	int32 unused_2;
};
ASSERT_STRUCT_SIZE(s_variant_setting_edit_reference, 24);

// max: k_maximum_default_variants
struct s_default_variant_definition
{
	string_id variant_name;

	e_default_variant_definition_type variant_type;

	tag_block<s_default_variant_setting> settings;

	e_game_variant_description_index description_index;

	int8 padding[3];
};
ASSERT_STRUCT_SIZE(s_default_variant_definition, 20);



struct s_multiplayer_variant_settings_interface_definition // goof
{
	tag_reference editing_screen_format; //wgit
	tag_reference quick_options_screen_format; //wgit
	tag_reference low_level_editing_list_screen_format; // wgit

	tag_block<s_variant_setting_edit_reference> game_engine_settings;

	// tag_ref: unic
	tag_reference default_variant_strings;

	tag_block<s_default_variant_definition> default_variants;

	s_default_variant_definition default_slayer_settings;

	s_default_variant_definition default_king_settings;

	s_default_variant_setting default_unused_settings;

	s_default_variant_definition default_oddball_settings;

	s_default_variant_definition default_juggernaut_settings;

	s_default_variant_definition default_unused_2_settings;

	s_default_variant_definition default_ctf_settings;

	s_default_variant_definition default_assault_settings;

	s_default_variant_definition default_territories_settings;

	int8 unused[152];
};
ASSERT_STRUCT_SIZE(s_multiplayer_variant_settings_interface_definition, 368);

// max: k_maximum_text_value_pairs_new_per_block
struct s_text_value_pair_reference_new
{
	c_flags_no_init<e_text_value_pair_reference_flags, uint32, k_text_value_pair_reference_flags_count> flags;

	int32 value;

	string_id label_string;
};
ASSERT_STRUCT_SIZE(s_text_value_pair_reference_new, 12);

struct s_text_value_pair_definition // sily
{
	e_default_variant_setting_category_type parameter;

	int32 pad;

	tag_reference string_list; // unic

	string_id title_text;
	string_id header_text;
	string_id description_test;

	tag_block<s_text_value_pair_reference_new> text_value_pairs;
};
ASSERT_STRUCT_SIZE(s_text_value_pair_definition, 36);